### ISSUE TITLE
Search Engine logo while search field hidden

### ISSUE THREAD

**Issue by ghost** [Noitidart/Homepage-New-Tab#1]
Bug:
Option "Hide search field" removes from homepage the search-field only, but not the search-engine logo. Please check the screenshots attached.

Browser:
Firefox 29 + ClassicThemeRestorer

![addon-settings](https://cloud.githubusercontent.com/assets/7574595/2965106/08394e84-daef-11e3-9247-241ea6d704bf.png)
![homepage](https://cloud.githubusercontent.com/assets/7574595/2965107/0b4956e6-daef-11e3-8df3-dfc4e204e9b8.png)

**Comment by Noitidart** [comment]
Thanks man for this detail I'll look into this. The picture helps a ton.

**Comment by Noitidart** [comment]
Hey @4looch it should be fixed now, please test it out by:
1. Install the addon "GitHub Extensions Installer" from here: https://addons.mozilla.org/en-US/firefox/addon/github-extension-installer/
2. Then go to my GitHub Repository for the future version of this addon:
   https://github.com/Noitidart/Homepage-New-Tab
3. And then click on "Add to Firefox" it will install the addon to Firefox. (this install its, then just use the addon like normal)
